/**
 * remotionAgentService.js
 * -----------------------------------------------------------------------------
 * A lean frontend-to-backend bridge. Forwards the user prompt and media metadata
 * to the Python FastAPI backend which handles the LLM orchestration (Groq/Gemini).
 * 
 * Returns the fully structured v2 contract JSON timeline generated by the backend,
 * after applying a strict client-side normalization pass (safety net).
 */

const ENDPOINT = 'http://localhost:8000/api/generate-timeline';
const FPS = 30;

/**
 * Forward the natural-language request to the Python backend.
 * @param {object} args
 * @param {string} args.userPrompt
 * @param {object} [args.context]  optional { transcript, width, height, uploads }
 * @returns {Promise<object>} normalized v2 timeline JSON.
 */
export async function generateRemotionTimeline({ userPrompt, context = {} }) {
  if (!userPrompt) throw new Error('remotionAgentService: missing userPrompt');

  const width = context.width || 1920;
  const height = context.height || 1080;

  const payload = {
    prompt: userPrompt,
    uploadedFiles: context.uploads || [],
    transcript: context.transcript || null,
    project: { width, height, fps: FPS }
  };

  const res = await fetch(ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    let detail = '';
    try { detail = await res.text(); } catch (e) {}
    throw new Error(`remotionAgentService: backend request failed (${res.status}) ${detail.slice(0, 160)}`);
  }

  const data = await res.json();
  
  // The backend might wrap the timeline in a specific field, or just return the schema directly.
  // We assume the backend returns the raw JSON timeline matching the REMOTION_TIMELINE_SCHEMA.
  const rawTimeline = data.timeline ? data : data.result ? data.result : data;

  return normalizeTimeline(rawTimeline, { width, height });
}

/* -------------------------------------------------------------------------- */

/** Clamp/repair so Remotion never receives invalid frames or missing fields. */
function normalizeTimeline(plan, { width, height }) {
  const fps = plan.projectSettings?.fps || FPS;

  const fixFrames = (item, i, prefix) => {
    const startFrame = Math.max(0, Math.round(item.startFrame || 0));
    const endFrame = Math.max(startFrame + 1, Math.round(item.endFrame || startFrame + fps));
    return { ...item, id: item.id || `${prefix}_${i}`, startFrame, endFrame };
  };

  const videoTrack = (plan.timeline?.videoTrack || []).map((t, i) => fixFrames(t, i, 'v')).sort(byStart);
  const audioTrack = (plan.timeline?.audioTrack || [])
    .map((t, i) => ({ ...fixFrames(t, i, 'a'), volume: clamp01(t.volume ?? (t.type === 'bg_music' ? 0.25 : 1)) }))
    .sort(byStart);
  const rawMg = (plan.timeline?.motionGraphicsTrack || [])
    .map((t, i) => {
      const fixed = fixFrames(t, i, 'mg');
      return {
        ...fixed,
        properties: {
          text: t.properties?.text || '',
          fontFamily: t.properties?.fontFamily || 'Montserrat',
          color: t.properties?.color || '#FFFFFF',
          fontSize: Math.max(12, Math.round(t.properties?.fontSize || 64)),
          animationEffect: t.properties?.animationEffect || 'fade-in',
          words: Array.isArray(t.properties?.words) ? t.properties.words : [],
        },
      };
    })
    .sort(byStart);

  // Auto-merge: if the model created one item per word (>8 items, all short,
  // same type), collapse them into sentence containers.
  const motionGraphicsTrack = mergeWordLevelItems(rawMg, fps);

  const lastFrame = [...videoTrack, ...audioTrack, ...motionGraphicsTrack].reduce(
    (m, t) => Math.max(m, t.endFrame),
    0,
  );

  return {
    projectSettings: {
      width: plan.projectSettings?.width || width,
      height: plan.projectSettings?.height || height,
      fps,
      totalDurationInFrames: Math.max(plan.projectSettings?.totalDurationInFrames || 0, lastFrame, fps),
    },
    aiGeneration: {
      voiceoverScript: plan.aiGeneration?.voiceoverScript || '',
      musicPrompt: plan.aiGeneration?.musicPrompt || '',
      imagePrompts: plan.aiGeneration?.imagePrompts || [],
      videoPrompts: plan.aiGeneration?.videoPrompts || [],
    },
    timeline: { videoTrack, audioTrack, motionGraphicsTrack },
  };
}

const byStart = (a, b) => a.startFrame - b.startFrame;
const clamp01 = (n) => Math.max(0, Math.min(1, Number(n) || 0));

/**
 * BULLETPROOF post-processor: if the model created one motionGraphicsTrack item
 * per word (regardless of count), collapse them into sentence/phrase containers
 * with embedded word timestamps.
 *
 * Strategy:
 *   Pass 1 — Detect: is this a word-per-item pattern? (avg words per item ≤ 2)
 *   Pass 2 — Group by sentence boundaries (punctuation: . ! ? :) and time gaps > 1s
 *   Pass 3 — Hard cap: if still >10 items, force-merge into ~5-word chunks
 *
 * Items that already have a valid words[] array are left untouched.
 */
function mergeWordLevelItems(items, fps) {
  if (items.length <= 2) return items; // 1-2 items is always fine

  // Separate items that already have proper word arrays from flat ones.
  const alreadyMerged = items.filter(
    (it) => Array.isArray(it.properties?.words) && it.properties.words.length > 1,
  );
  const flat = items.filter(
    (it) => !Array.isArray(it.properties?.words) || it.properties.words.length <= 1,
  );

  // If nothing to merge, return as-is.
  if (flat.length <= 2) return items;

  // Pass 1 — Detect word-per-item pattern.
  // Calculate average word count per item.
  const totalWords = flat.reduce(
    (sum, it) => sum + (it.properties?.text || '').trim().split(/\s+/).length,
    0,
  );
  const avgWordsPerItem = totalWords / flat.length;

  // If average > 4 words per item AND fewer than 8 items, it's probably real sentences.
  if (avgWordsPerItem > 4 && flat.length <= 8) {
    return items; // looks like proper sentence-level items already
  }

  // If only 3-4 items but each is a full sentence, leave them alone.
  if (flat.length <= 4 && avgWordsPerItem > 3) {
    return items;
  }

  // Pass 2 — Group into sentences using punctuation and time gaps.
  const sentences = [];
  let current = null;

  for (const item of flat) {
    const text = (item.properties?.text || '').trim();
    const gap = current ? (item.startFrame - current.endFrame) : 0;

    // Start a new sentence group when:
    // - First item
    // - Type changes
    // - Time gap > 1 second (30 frames)
    // - Previous item's text ended with sentence-ending punctuation
    const gapTooLarge = gap > fps * 1.0;
    const typeChanged = current && current.type !== item.type;
    const prevEndedSentence = current &&
      /[.!?:]\s*$/.test(current.properties.text);
    // Also split if current group already has many words (> 12)
    const groupTooLong = current && current.properties.words.length >= 12;

    if (!current || typeChanged || gapTooLarge || prevEndedSentence || groupTooLong) {
      if (current) sentences.push(current);
      current = {
        id: `mg_sentence_${sentences.length}`,
        type: item.type,
        startFrame: item.startFrame,
        endFrame: item.endFrame,
        properties: {
          text: text,
          fontFamily: item.properties?.fontFamily || 'Montserrat',
          color: item.properties?.color || '#FFFFFF',
          fontSize: item.properties?.fontSize || 64,
          animationEffect: item.properties?.animationEffect || 'pop-bounce',
          words: [{
            word: text,
            startFrame: item.startFrame,
            endFrame: item.endFrame,
          }],
        },
      };
    } else {
      // Merge into current sentence group.
      current.endFrame = Math.max(current.endFrame, item.endFrame);
      current.properties.text += ' ' + text;
      current.properties.words.push({
        word: text,
        startFrame: item.startFrame,
        endFrame: item.endFrame,
      });
    }
  }
  if (current) sentences.push(current);

  // Pass 3 — Hard cap: if still > 10 items, force-merge into ~5-word chunks.
  let result = sentences;
  if (result.length > 10) {
    const forced = [];
    let chunk = null;
    for (const item of result) {
      if (!chunk) {
        chunk = { ...item, properties: { ...item.properties, words: [...item.properties.words] } };
      } else {
        chunk.endFrame = Math.max(chunk.endFrame, item.endFrame);
        chunk.properties.text += ' ' + item.properties.text;
        chunk.properties.words.push(...item.properties.words);
      }
      // Flush every 5 words or at sentence boundaries
      const totalWordCount = chunk.properties.words.length;
      if (totalWordCount >= 5 || /[.!?:]\s*$/.test(chunk.properties.text)) {
        chunk.id = `mg_forced_${forced.length}`;
        forced.push(chunk);
        chunk = null;
      }
    }
    if (chunk) {
      chunk.id = `mg_forced_${forced.length}`;
      forced.push(chunk);
    }
    result = forced;
  }

  // Combine with items that already had proper word arrays.
  return [...alreadyMerged, ...result].sort(byStart);
}
